language: ruby

services:
  - postgresql

env:
  - DATABASE_URL=postgres://localhost RAILS_ENV=test

before_install:
  - gem update --system

install:
  - bundle install

before_script:
  - rails db:setup # reset, migrate, seed

script:
  - rails test
