language: ruby

services:
  - postgresql

# get all the gems and store them globally
before_install:
  - gem update --system

# put a bow on all the gems
install:
  - bundle install

# fire off a database creation
before_script:
  - psql -c 'create database political_ties_test;' -U postgres

# run the app tests
script:
  - rails test